apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: controle-estoque-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/RafaelGabriel325/api-controle-de-estoque.git
    targetRevision: main
    path: helm/controle-estoque
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
