apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ce-pg-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/RafaelGabriel325/api-controle-de-estoque.git
    targetRevision: main
    path: argocd-gitops/db/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
